### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by IAmV0id** [dslul/logiconf#4] opened 2019-12-08 07:11 UTC
I did everything else, but when I had to run sh install.sh . Nothing happened, I just got 
NAME@COMPUTER_NAME:~/logiconf$ sh install.sh
sudo: unable to resolve host hal-9000: Name or service not known
sudo: unable to resolve host hal-9000: Name or service not known
sudo: unable to resolve host hal-9000: Name or service not known

running it as sudo didnt help either, can someone help me?

**Comment by dslul** [comment] 2019-12-08 07:37
Hi, can you check if the command inside install.sh was executed? Do the following:
`cat /etc/udev/rules.d/99-hidraw-logitech.rules`

**Comment by IAmV0id** [comment] 2019-12-08 08:19
I got
a_random_lantern@hal-9000:~$ cat /etc/udev/rules.d/99-hidraw-logitech.rules
KERNEL=="hidraw*", ATTRS{idVendor}=="046d", MODE="0666"

So yes, I guess so. I also looked inside the file and saw it.

**Comment by dslul** [comment] 2019-12-08 08:51
Good, you can try to start the program then. You can compile or download it from the releases tab

**Comment by IAmV0id** [comment] 2019-12-08 10:23
What file or text should I enter to do so then? I'm not seeing anything to run. Sorry if I'm sounding stupid

**Comment by dslul** [comment] 2019-12-08 10:27
No problem, here is the link https://github.com/dslul/logiconf/releases
Let me know if it works

**Comment by IAmV0id** [comment] 2019-12-08 10:33
I already downloaded it, how should I run this gui file? It won't launch when I clicked, even after I made it launch as a program.

**Comment by dslul** [comment] 2019-12-08 10:40
Can you try to launch it from terminal and report here any errors? What distro are you using?

**Comment by IAmV0id** [comment] 2019-12-08 10:46
I'm using ubuntu 19.10, Pop!_OS. And I don't seem to have a option to run it in terminal. And it doesn't seem that the file has a extension to it.

**Comment by dslul** [comment] 2019-12-08 13:35
just set the file as executable (logiconf-gui) and then do `./logiconf-gui` from terminal (be sure to be in the folder where the file is located)

**Comment by IAmV0id** [comment] 2019-12-08 16:15
a_random_lantern@hal-9000:~/logiconf/logiconf-gui$ ./logiconf-gui
/dev/hidraw5
terminate called after throwing an instance of 'std::range_error'
  what():  wstring_convert::to_bytes
Aborted (core dumped)

Got this error when doing so

**Comment by dslul** [comment] 2019-12-09 07:58
What mouse model do you have?

**Comment by IAmV0id** [comment] 2019-12-09 13:50
The G402, same one as yours

**Comment by dslul** [comment] 2019-12-09 15:21
Well this is unsual, do you happen to have any other logitech devices connected? At this point I think the program is trying to talk to the wrong device. Could you please download [this set of tools](https://github.com/dslul/logiconf/files/3940340/hidpp-tools.zip), unzip it and then run these commands in the folder? Thank you.
`./hidpp-list-devices`
`./hidpp-list-features /dev/hidraw5`

**Comment by IAmV0id** [comment] 2019-12-09 21:50
```
a_random_lantern@hal-9000:~/Downloads/hidpp-tools$ ./hidpp-list-devices
/dev/hidraw5: Logitech Gaming Mouse G402 (046d:c07e) HID++ 4.2
a_random_lantern@hal-9000:~/Downloads/hidpp-tools$  ./hidpp-list-features /dev/hidraw5
Logitech Gaming Mouse G402 (046d:c07e) is a HID++ 4.2 device
Feature 0x01: [0x0001] Feature set
Feature 0x02: [0x0003] Device FW version
Feature 0x03: [0x0005] Device name
Feature 0x04: [0x00c1] DFUcontrol 2
Feature 0x05: [0x1300] LED control
Feature 0x06: [0x1801] ? (hidden, internal)
Feature 0x07: [0x1802] Device reset (hidden, internal)
Feature 0x08: [0x1850] ? (hidden, internal)
Feature 0x09: [0x18a1] ? (hidden, internal)
Feature 0x0a: [0x1e00] Enable hidden features (hidden)
Feature 0x0b: [0x1eb0] ? (hidden, internal)
Feature 0x0c: [0x2201] Adjustable dpi
Feature 0x0d: [0x2400] Hybrid tracking
Feature 0x0e: [0x8060] Report rate
Feature 0x0f: [0x8100] Onboard profiles
Feature 0x10: [0x8110] Mouse button spy
```

This is what I got, the mouse is the only logitech thing I own connected to my pc

**Comment by dslul** [comment] 2019-12-10 07:36
It seems to be completely the same, and I still can't reproduce your problems, so I guess maybe the libraries are different? I've built an AppImage that bundles everything inside, you can find it [here](https://github.com/dslul/logiconf/releases/download/0.2.1/logiconf-x86_64.AppImage). Just set it as executable and start it.

**Comment by IAmV0id** [comment] 2019-12-10 13:48
Ah thank you, the appimage works. Odd how I can't do it the other way tho

**Comment by dslul** [comment] 2019-12-10 14:18
I think you have some shared libraries that differ too much from the ones this program was built for. If you encounter any other problem, don't hesitate to open another issue. I'll close this one.

**Closed as completed by dslul** 2019-12-10 14:18 UTC
